// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bot_admins.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInviteToken = `-- name: CreateInviteToken :exec
INSERT INTO bot_invite_tokens(token) VALUES($1)
`

func (q *Queries) CreateInviteToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, createInviteToken, token)
	return err
}

const getInviteTokenUsedBy = `-- name: GetInviteTokenUsedBy :one
SELECT used_by FROM bot_invite_tokens WHERE token=$1
`

func (q *Queries) GetInviteTokenUsedBy(ctx context.Context, token string) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getInviteTokenUsedBy, token)
	var used_by pgtype.Int8
	err := row.Scan(&used_by)
	return used_by, err
}

const hasAnyBotAdmin = `-- name: HasAnyBotAdmin :one
SELECT EXISTS(SELECT 1 FROM bot_admins)
`

func (q *Queries) HasAnyBotAdmin(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasAnyBotAdmin)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isBotAdmin = `-- name: IsBotAdmin :one
SELECT EXISTS(SELECT 1 FROM bot_admins WHERE telegram_id=$1)
`

func (q *Queries) IsBotAdmin(ctx context.Context, telegramID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isBotAdmin, telegramID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBotAdmins = `-- name: ListBotAdmins :many
SELECT telegram_id, telegram_name, added_at FROM bot_admins ORDER BY added_at
`

func (q *Queries) ListBotAdmins(ctx context.Context) ([]BotAdmin, error) {
	rows, err := q.db.Query(ctx, listBotAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotAdmin
	for rows.Next() {
		var i BotAdmin
		if err := rows.Scan(&i.TelegramID, &i.TelegramName, &i.AddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteTokenUsed = `-- name: MarkInviteTokenUsed :exec
UPDATE bot_invite_tokens SET used_by=$1, used_at=NOW() WHERE token=$2
`

type MarkInviteTokenUsedParams struct {
	UsedBy pgtype.Int8 `json:"used_by"`
	Token  string      `json:"token"`
}

func (q *Queries) MarkInviteTokenUsed(ctx context.Context, arg MarkInviteTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markInviteTokenUsed, arg.UsedBy, arg.Token)
	return err
}

const removeBotAdmin = `-- name: RemoveBotAdmin :exec
DELETE FROM bot_admins WHERE telegram_id=$1
`

func (q *Queries) RemoveBotAdmin(ctx context.Context, telegramID int64) error {
	_, err := q.db.Exec(ctx, removeBotAdmin, telegramID)
	return err
}

const upsertBotAdmin = `-- name: UpsertBotAdmin :exec
INSERT INTO bot_admins(telegram_id, telegram_name) VALUES($1, $2)
ON CONFLICT(telegram_id) DO UPDATE SET telegram_name=$2
`

type UpsertBotAdminParams struct {
	TelegramID   int64  `json:"telegram_id"`
	TelegramName string `json:"telegram_name"`
}

func (q *Queries) UpsertBotAdmin(ctx context.Context, arg UpsertBotAdminParams) error {
	_, err := q.db.Exec(ctx, upsertBotAdmin, arg.TelegramID, arg.TelegramName)
	return err
}
