// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exit_nodes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEnabledExitNodeDuplicate = `-- name: CountEnabledExitNodeDuplicate :one
SELECT COUNT(*)::int FROM exit_nodes WHERE enabled=TRUE AND address=$1 AND port=$2 AND id<>$3
`

type CountEnabledExitNodeDuplicateParams struct {
	Address string      `json:"address"`
	Port    int32       `json:"port"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) CountEnabledExitNodeDuplicate(ctx context.Context, arg CountEnabledExitNodeDuplicateParams) (int32, error) {
	row := q.db.QueryRow(ctx, countEnabledExitNodeDuplicate, arg.Address, arg.Port, arg.ID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countEnabledExitNodes = `-- name: CountEnabledExitNodes :one
SELECT COUNT(*)::int FROM exit_nodes WHERE enabled=TRUE
`

func (q *Queries) CountEnabledExitNodes(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countEnabledExitNodes)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countEnabledExitNodesByAddressPort = `-- name: CountEnabledExitNodesByAddressPort :one
SELECT COUNT(*)::int FROM exit_nodes WHERE enabled=TRUE AND address=$1 AND port=$2
`

type CountEnabledExitNodesByAddressPortParams struct {
	Address string `json:"address"`
	Port    int32  `json:"port"`
}

func (q *Queries) CountEnabledExitNodesByAddressPort(ctx context.Context, arg CountEnabledExitNodesByAddressPortParams) (int32, error) {
	row := q.db.QueryRow(ctx, countEnabledExitNodesByAddressPort, arg.Address, arg.Port)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countExitNodesByTunnelUUID = `-- name: CountExitNodesByTunnelUUID :one
SELECT COUNT(*)::int FROM exit_nodes WHERE tunnel_uuid=$1
`

func (q *Queries) CountExitNodesByTunnelUUID(ctx context.Context, tunnelUuid string) (int32, error) {
	row := q.db.QueryRow(ctx, countExitNodesByTunnelUUID, tunnelUuid)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteExitNode = `-- name: DeleteExitNode :execrows
DELETE FROM exit_nodes WHERE id=$1
`

func (q *Queries) DeleteExitNode(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExitNode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findExitNodeByAddressPort = `-- name: FindExitNodeByAddressPort :one
SELECT id FROM exit_nodes WHERE address=$1 AND port=$2
`

type FindExitNodeByAddressPortParams struct {
	Address string `json:"address"`
	Port    int32  `json:"port"`
}

func (q *Queries) FindExitNodeByAddressPort(ctx context.Context, arg FindExitNodeByAddressPortParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findExitNodeByAddressPort, arg.Address, arg.Port)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findExitNodeByTunnelUUID = `-- name: FindExitNodeByTunnelUUID :one
SELECT id FROM exit_nodes WHERE tunnel_uuid=$1
`

func (q *Queries) FindExitNodeByTunnelUUID(ctx context.Context, tunnelUuid string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findExitNodeByTunnelUUID, tunnelUuid)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getExitNode = `-- name: GetExitNode :one
SELECT id, name, address, port, tunnel_uuid, pinned_peer_cert_sha256, priority, enabled, created_at, updated_at
FROM exit_nodes WHERE id=$1
`

type GetExitNodeRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	Address              string             `json:"address"`
	Port                 int32              `json:"port"`
	TunnelUuid           string             `json:"tunnel_uuid"`
	PinnedPeerCertSha256 string             `json:"pinned_peer_cert_sha256"`
	Priority             int32              `json:"priority"`
	Enabled              bool               `json:"enabled"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetExitNode(ctx context.Context, id pgtype.UUID) (GetExitNodeRow, error) {
	row := q.db.QueryRow(ctx, getExitNode, id)
	var i GetExitNodeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Port,
		&i.TunnelUuid,
		&i.PinnedPeerCertSha256,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertExitNode = `-- name: InsertExitNode :one
INSERT INTO exit_nodes(id, name, address, port, tunnel_uuid, pinned_peer_cert_sha256, priority, enabled)
VALUES($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, name, address, port, tunnel_uuid, pinned_peer_cert_sha256, priority, enabled, created_at, updated_at
`

type InsertExitNodeParams struct {
	ID                   pgtype.UUID `json:"id"`
	Name                 string      `json:"name"`
	Address              string      `json:"address"`
	Port                 int32       `json:"port"`
	TunnelUuid           string      `json:"tunnel_uuid"`
	PinnedPeerCertSha256 string      `json:"pinned_peer_cert_sha256"`
	Priority             int32       `json:"priority"`
	Enabled              bool        `json:"enabled"`
}

type InsertExitNodeRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	Address              string             `json:"address"`
	Port                 int32              `json:"port"`
	TunnelUuid           string             `json:"tunnel_uuid"`
	PinnedPeerCertSha256 string             `json:"pinned_peer_cert_sha256"`
	Priority             int32              `json:"priority"`
	Enabled              bool               `json:"enabled"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertExitNode(ctx context.Context, arg InsertExitNodeParams) (InsertExitNodeRow, error) {
	row := q.db.QueryRow(ctx, insertExitNode,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Port,
		arg.TunnelUuid,
		arg.PinnedPeerCertSha256,
		arg.Priority,
		arg.Enabled,
	)
	var i InsertExitNodeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Port,
		&i.TunnelUuid,
		&i.PinnedPeerCertSha256,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExitNodes = `-- name: ListExitNodes :many
SELECT id, name, address, port, tunnel_uuid, pinned_peer_cert_sha256, priority, enabled, created_at, updated_at
FROM exit_nodes ORDER BY priority ASC, created_at ASC
`

type ListExitNodesRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	Address              string             `json:"address"`
	Port                 int32              `json:"port"`
	TunnelUuid           string             `json:"tunnel_uuid"`
	PinnedPeerCertSha256 string             `json:"pinned_peer_cert_sha256"`
	Priority             int32              `json:"priority"`
	Enabled              bool               `json:"enabled"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListExitNodes(ctx context.Context) ([]ListExitNodesRow, error) {
	rows, err := q.db.Query(ctx, listExitNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExitNodesRow
	for rows.Next() {
		var i ListExitNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Port,
			&i.TunnelUuid,
			&i.PinnedPeerCertSha256,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeExitByAddressPort = `-- name: MergeExitByAddressPort :exec
UPDATE exit_nodes SET
  name=$2,
  tunnel_uuid=CASE WHEN $3<>'' THEN $3 ELSE tunnel_uuid END,
  pinned_peer_cert_sha256=CASE WHEN $4<>'' THEN $4 ELSE pinned_peer_cert_sha256 END,
  priority=CASE WHEN $5>0 THEN $5 ELSE priority END,
  enabled=$6,
  updated_at=$7
WHERE id=$1
`

type MergeExitByAddressPortParams struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Column3   interface{}        `json:"column_3"`
	Column4   interface{}        `json:"column_4"`
	Column5   interface{}        `json:"column_5"`
	Enabled   bool               `json:"enabled"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MergeExitByAddressPort(ctx context.Context, arg MergeExitByAddressPortParams) error {
	_, err := q.db.Exec(ctx, mergeExitByAddressPort,
		arg.ID,
		arg.Name,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Enabled,
		arg.UpdatedAt,
	)
	return err
}

const mergeExitByTunnelUUID = `-- name: MergeExitByTunnelUUID :exec
UPDATE exit_nodes SET
  name=$2,
  pinned_peer_cert_sha256=CASE WHEN $3<>'' THEN $3 ELSE pinned_peer_cert_sha256 END,
  priority=CASE WHEN $4>0 THEN $4 ELSE priority END,
  enabled=$5,
  updated_at=$6
WHERE id=$1
`

type MergeExitByTunnelUUIDParams struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Column3   interface{}        `json:"column_3"`
	Column4   interface{}        `json:"column_4"`
	Enabled   bool               `json:"enabled"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MergeExitByTunnelUUID(ctx context.Context, arg MergeExitByTunnelUUIDParams) error {
	_, err := q.db.Exec(ctx, mergeExitByTunnelUUID,
		arg.ID,
		arg.Name,
		arg.Column3,
		arg.Column4,
		arg.Enabled,
		arg.UpdatedAt,
	)
	return err
}

const updateExitNode = `-- name: UpdateExitNode :one
UPDATE exit_nodes SET name=$2, address=$3, port=$4, priority=$5, enabled=$6, updated_at=$7
WHERE id=$1
RETURNING id, name, address, port, tunnel_uuid, pinned_peer_cert_sha256, priority, enabled, created_at, updated_at
`

type UpdateExitNodeParams struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Address   string             `json:"address"`
	Port      int32              `json:"port"`
	Priority  int32              `json:"priority"`
	Enabled   bool               `json:"enabled"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UpdateExitNodeRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	Address              string             `json:"address"`
	Port                 int32              `json:"port"`
	TunnelUuid           string             `json:"tunnel_uuid"`
	PinnedPeerCertSha256 string             `json:"pinned_peer_cert_sha256"`
	Priority             int32              `json:"priority"`
	Enabled              bool               `json:"enabled"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateExitNode(ctx context.Context, arg UpdateExitNodeParams) (UpdateExitNodeRow, error) {
	row := q.db.QueryRow(ctx, updateExitNode,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Port,
		arg.Priority,
		arg.Enabled,
		arg.UpdatedAt,
	)
	var i UpdateExitNodeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Port,
		&i.TunnelUuid,
		&i.PinnedPeerCertSha256,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
