// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leak.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const connectionsByBuckets1d = `-- name: ConnectionsByBuckets1d :many
SELECT date_trunc('day', last_seen_at)::timestamptz AS bucket_start,
  COUNT(DISTINCT ip)::int AS ips
FROM user_ip_observations
WHERE user_uuid=$1 AND last_seen_at >= NOW() - $2::interval
GROUP BY bucket_start
ORDER BY bucket_start
`

type ConnectionsByBuckets1dParams struct {
	UserUuid pgtype.UUID     `json:"user_uuid"`
	Column2  pgtype.Interval `json:"column_2"`
}

type ConnectionsByBuckets1dRow struct {
	BucketStart pgtype.Timestamptz `json:"bucket_start"`
	Ips         int32              `json:"ips"`
}

func (q *Queries) ConnectionsByBuckets1d(ctx context.Context, arg ConnectionsByBuckets1dParams) ([]ConnectionsByBuckets1dRow, error) {
	rows, err := q.db.Query(ctx, connectionsByBuckets1d, arg.UserUuid, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectionsByBuckets1dRow
	for rows.Next() {
		var i ConnectionsByBuckets1dRow
		if err := rows.Scan(&i.BucketStart, &i.Ips); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const connectionsByBuckets1h = `-- name: ConnectionsByBuckets1h :many
SELECT date_trunc('hour', last_seen_at)::timestamptz AS bucket_start,
  COUNT(DISTINCT ip)::int AS ips
FROM user_ip_observations
WHERE user_uuid=$1 AND last_seen_at >= NOW() - $2::interval
GROUP BY bucket_start
ORDER BY bucket_start
`

type ConnectionsByBuckets1hParams struct {
	UserUuid pgtype.UUID     `json:"user_uuid"`
	Column2  pgtype.Interval `json:"column_2"`
}

type ConnectionsByBuckets1hRow struct {
	BucketStart pgtype.Timestamptz `json:"bucket_start"`
	Ips         int32              `json:"ips"`
}

func (q *Queries) ConnectionsByBuckets1h(ctx context.Context, arg ConnectionsByBuckets1hParams) ([]ConnectionsByBuckets1hRow, error) {
	rows, err := q.db.Query(ctx, connectionsByBuckets1h, arg.UserUuid, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectionsByBuckets1hRow
	for rows.Next() {
		var i ConnectionsByBuckets1hRow
		if err := rows.Scan(&i.BucketStart, &i.Ips); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const connectionsByBuckets5m = `-- name: ConnectionsByBuckets5m :many
SELECT (date_trunc('hour', last_seen_at) + ((extract(minute from last_seen_at)::int / 5) * interval '5 minutes'))::timestamptz AS bucket_start,
  COUNT(DISTINCT ip)::int AS ips
FROM user_ip_observations
WHERE user_uuid=$1 AND last_seen_at >= NOW() - $2::interval
GROUP BY bucket_start
ORDER BY bucket_start
`

type ConnectionsByBuckets5mParams struct {
	UserUuid pgtype.UUID     `json:"user_uuid"`
	Column2  pgtype.Interval `json:"column_2"`
}

type ConnectionsByBuckets5mRow struct {
	BucketStart pgtype.Timestamptz `json:"bucket_start"`
	Ips         int32              `json:"ips"`
}

func (q *Queries) ConnectionsByBuckets5m(ctx context.Context, arg ConnectionsByBuckets5mParams) ([]ConnectionsByBuckets5mRow, error) {
	rows, err := q.db.Query(ctx, connectionsByBuckets5m, arg.UserUuid, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectionsByBuckets5mRow
	for rows.Next() {
		var i ConnectionsByBuckets5mRow
		if err := rows.Scan(&i.BucketStart, &i.Ips); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const connectionsByBuckets6h = `-- name: ConnectionsByBuckets6h :many
SELECT (date_trunc('day', last_seen_at) + ((extract(hour from last_seen_at)::int / 6) * interval '6 hours'))::timestamptz AS bucket_start,
  COUNT(DISTINCT ip)::int AS ips
FROM user_ip_observations
WHERE user_uuid=$1 AND last_seen_at >= NOW() - $2::interval
GROUP BY bucket_start
ORDER BY bucket_start
`

type ConnectionsByBuckets6hParams struct {
	UserUuid pgtype.UUID     `json:"user_uuid"`
	Column2  pgtype.Interval `json:"column_2"`
}

type ConnectionsByBuckets6hRow struct {
	BucketStart pgtype.Timestamptz `json:"bucket_start"`
	Ips         int32              `json:"ips"`
}

func (q *Queries) ConnectionsByBuckets6h(ctx context.Context, arg ConnectionsByBuckets6hParams) ([]ConnectionsByBuckets6hRow, error) {
	rows, err := q.db.Query(ctx, connectionsByBuckets6h, arg.UserUuid, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectionsByBuckets6hRow
	for rows.Next() {
		var i ConnectionsByBuckets6hRow
		if err := rows.Scan(&i.BucketStart, &i.Ips); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countConcurrentIPs = `-- name: CountConcurrentIPs :one
SELECT COUNT(*)::int FROM user_ip_observations
WHERE user_uuid=$1 AND last_seen_at >= NOW() - $2::interval
`

type CountConcurrentIPsParams struct {
	UserUuid pgtype.UUID     `json:"user_uuid"`
	Column2  pgtype.Interval `json:"column_2"`
}

func (q *Queries) CountConcurrentIPs(ctx context.Context, arg CountConcurrentIPsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countConcurrentIPs, arg.UserUuid, arg.Column2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUniqueIPs = `-- name: CountUniqueIPs :one
SELECT COUNT(DISTINCT ip)::int FROM user_ip_observations
WHERE user_uuid=$1 AND last_seen_at >= NOW() - $2::interval
`

type CountUniqueIPsParams struct {
	UserUuid pgtype.UUID     `json:"user_uuid"`
	Column2  pgtype.Interval `json:"column_2"`
}

func (q *Queries) CountUniqueIPs(ctx context.Context, arg CountUniqueIPsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUniqueIPs, arg.UserUuid, arg.Column2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertLeakSignal = `-- name: InsertLeakSignal :exec
INSERT INTO user_leak_signals(user_uuid, kind, score, detail)
VALUES($1, $2, $3, $4)
`

type InsertLeakSignalParams struct {
	UserUuid pgtype.UUID `json:"user_uuid"`
	Kind     string      `json:"kind"`
	Score    int32       `json:"score"`
	Detail   []byte      `json:"detail"`
}

func (q *Queries) InsertLeakSignal(ctx context.Context, arg InsertLeakSignalParams) error {
	_, err := q.db.Exec(ctx, insertLeakSignal,
		arg.UserUuid,
		arg.Kind,
		arg.Score,
		arg.Detail,
	)
	return err
}

const recentUserLeakSignals = `-- name: RecentUserLeakSignals :many
SELECT id, user_uuid, kind, score, detail, created_at
FROM user_leak_signals
WHERE user_uuid=$1
ORDER BY created_at DESC
LIMIT $2
`

type RecentUserLeakSignalsParams struct {
	UserUuid pgtype.UUID `json:"user_uuid"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) RecentUserLeakSignals(ctx context.Context, arg RecentUserLeakSignalsParams) ([]UserLeakSignal, error) {
	rows, err := q.db.Query(ctx, recentUserLeakSignals, arg.UserUuid, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserLeakSignal
	for rows.Next() {
		var i UserLeakSignal
		if err := rows.Scan(
			&i.ID,
			&i.UserUuid,
			&i.Kind,
			&i.Score,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserIPObservation = `-- name: UpsertUserIPObservation :exec
INSERT INTO user_ip_observations(user_uuid, ip, first_seen_at, last_seen_at, sessions_seen)
VALUES($1, $2, NOW(), NOW(), 1)
ON CONFLICT (user_uuid, ip) DO UPDATE SET
  last_seen_at=NOW(),
  sessions_seen=user_ip_observations.sessions_seen+1
`

type UpsertUserIPObservationParams struct {
	UserUuid pgtype.UUID `json:"user_uuid"`
	Ip       netip.Addr  `json:"ip"`
}

func (q *Queries) UpsertUserIPObservation(ctx context.Context, arg UpsertUserIPObservationParams) error {
	_, err := q.db.Exec(ctx, upsertUserIPObservation, arg.UserUuid, arg.Ip)
	return err
}
