// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelVPNInvite = `-- name: CancelVPNInvite :execrows
UPDATE vpn_invites SET cancelled_at=NOW() WHERE id=$1 AND used_at IS NULL AND cancelled_at IS NULL
`

func (q *Queries) CancelVPNInvite(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, cancelVPNInvite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMember = `-- name: GetMember :one
SELECT uuid::text, telegram_id, name, is_active, enrollment_source, enrolled_at, member_pending,
 preferred_exit_id::text FROM users WHERE telegram_id=$1 AND enrollment_source IS NOT NULL
`

type GetMemberRow struct {
	Uuid             string             `json:"uuid"`
	TelegramID       pgtype.Int8        `json:"telegram_id"`
	Name             string             `json:"name"`
	IsActive         bool               `json:"is_active"`
	EnrollmentSource pgtype.Text        `json:"enrollment_source"`
	EnrolledAt       pgtype.Timestamptz `json:"enrolled_at"`
	MemberPending    bool               `json:"member_pending"`
	PreferredExitID  string             `json:"preferred_exit_id"`
}

func (q *Queries) GetMember(ctx context.Context, telegramID pgtype.Int8) (GetMemberRow, error) {
	row := q.db.QueryRow(ctx, getMember, telegramID)
	var i GetMemberRow
	err := row.Scan(
		&i.Uuid,
		&i.TelegramID,
		&i.Name,
		&i.IsActive,
		&i.EnrollmentSource,
		&i.EnrolledAt,
		&i.MemberPending,
		&i.PreferredExitID,
	)
	return i, err
}

const getVPNGroup = `-- name: GetVPNGroup :one
SELECT chat_id, title, code, enabled FROM vpn_group WHERE singleton=true
`

type GetVPNGroupRow struct {
	ChatID  int64  `json:"chat_id"`
	Title   string `json:"title"`
	Code    string `json:"code"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) GetVPNGroup(ctx context.Context) (GetVPNGroupRow, error) {
	row := q.db.QueryRow(ctx, getVPNGroup)
	var i GetVPNGroupRow
	err := row.Scan(
		&i.ChatID,
		&i.Title,
		&i.Code,
		&i.Enabled,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT uuid::text, telegram_id, name, is_active, enrollment_source, enrolled_at, member_pending,
 preferred_exit_id::text FROM users WHERE enrollment_source IS NOT NULL ORDER BY enrolled_at
`

type ListMembersRow struct {
	Uuid             string             `json:"uuid"`
	TelegramID       pgtype.Int8        `json:"telegram_id"`
	Name             string             `json:"name"`
	IsActive         bool               `json:"is_active"`
	EnrollmentSource pgtype.Text        `json:"enrollment_source"`
	EnrolledAt       pgtype.Timestamptz `json:"enrolled_at"`
	MemberPending    bool               `json:"member_pending"`
	PreferredExitID  string             `json:"preferred_exit_id"`
}

func (q *Queries) ListMembers(ctx context.Context) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.Uuid,
			&i.TelegramID,
			&i.Name,
			&i.IsActive,
			&i.EnrollmentSource,
			&i.EnrolledAt,
			&i.MemberPending,
			&i.PreferredExitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVPNInvites = `-- name: ListVPNInvites :many
SELECT id,recipient,created_by,created_at,expires_at,used_at,cancelled_at FROM vpn_invites ORDER BY id DESC LIMIT 200
`

type ListVPNInvitesRow struct {
	ID          int64              `json:"id"`
	Recipient   int64              `json:"recipient"`
	CreatedBy   int64              `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	UsedAt      pgtype.Timestamptz `json:"used_at"`
	CancelledAt pgtype.Timestamptz `json:"cancelled_at"`
}

func (q *Queries) ListVPNInvites(ctx context.Context) ([]ListVPNInvitesRow, error) {
	rows, err := q.db.Query(ctx, listVPNInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVPNInvitesRow
	for rows.Next() {
		var i ListVPNInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Recipient,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putVPNGroup = `-- name: PutVPNGroup :exec
INSERT INTO vpn_group(singleton,chat_id,title,code,enabled,updated_by) VALUES(true,$1,$2,$3,$4,$5)
ON CONFLICT(singleton) DO UPDATE SET chat_id=EXCLUDED.chat_id,title=EXCLUDED.title,
code=EXCLUDED.code,enabled=EXCLUDED.enabled,updated_by=EXCLUDED.updated_by
`

type PutVPNGroupParams struct {
	ChatID    int64  `json:"chat_id"`
	Title     string `json:"title"`
	Code      string `json:"code"`
	Enabled   bool   `json:"enabled"`
	UpdatedBy int64  `json:"updated_by"`
}

func (q *Queries) PutVPNGroup(ctx context.Context, arg PutVPNGroupParams) error {
	_, err := q.db.Exec(ctx, putVPNGroup,
		arg.ChatID,
		arg.Title,
		arg.Code,
		arg.Enabled,
		arg.UpdatedBy,
	)
	return err
}
