// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AlertState struct {
	DedupeKey            string             `json:"dedupe_key"`
	Type                 string             `json:"type"`
	Severity             string             `json:"severity"`
	Channel              string             `json:"channel"`
	Status               string             `json:"status"`
	ConsecutiveFailures  int32              `json:"consecutive_failures"`
	ConsecutiveSuccesses int32              `json:"consecutive_successes"`
	LastSeenAt           pgtype.Timestamptz `json:"last_seen_at"`
	LastSentAt           pgtype.Timestamptz `json:"last_sent_at"`
	LastPayload          []byte             `json:"last_payload"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type BotAdmin struct {
	TelegramID   int64              `json:"telegram_id"`
	TelegramName string             `json:"telegram_name"`
	AddedAt      pgtype.Timestamptz `json:"added_at"`
}

type BotInviteToken struct {
	Token     string             `json:"token"`
	UsedBy    pgtype.Int8        `json:"used_by"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ExitNode struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	Address              string             `json:"address"`
	Port                 int32              `json:"port"`
	TunnelUuid           string             `json:"tunnel_uuid"`
	Priority             int32              `json:"priority"`
	Enabled              bool               `json:"enabled"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	PinnedPeerCertSha256 string             `json:"pinned_peer_cert_sha256"`
	CountryCode          string             `json:"country_code"`
	CountryName          string             `json:"country_name"`
	City                 string             `json:"city"`
	DisplayName          string             `json:"display_name"`
}

type MonthlyTraffic struct {
	UserUuid      pgtype.UUID        `json:"user_uuid"`
	Year          int32              `json:"year"`
	Month         int32              `json:"month"`
	UplinkBytes   int64              `json:"uplink_bytes"`
	DownlinkBytes int64              `json:"downlink_bytes"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Notification struct {
	ID         int64              `json:"id"`
	UserUuid   pgtype.UUID        `json:"user_uuid"`
	TelegramID int64              `json:"telegram_id"`
	Type       string             `json:"type"`
	Payload    []byte             `json:"payload"`
	SentAt     pgtype.Timestamptz `json:"sent_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type TrafficStat struct {
	ID            int64              `json:"id"`
	UserUuid      pgtype.UUID        `json:"user_uuid"`
	CollectedAt   pgtype.Timestamptz `json:"collected_at"`
	UplinkBytes   int64              `json:"uplink_bytes"`
	DownlinkBytes int64              `json:"downlink_bytes"`
}

type User struct {
	Uuid                 pgtype.UUID        `json:"uuid"`
	Name                 string             `json:"name"`
	TelegramID           pgtype.Int8        `json:"telegram_id"`
	TelegramUsername     pgtype.Text        `json:"telegram_username"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	IsActive             bool               `json:"is_active"`
	DisabledAt           pgtype.Timestamptz `json:"disabled_at"`
	LeakPolicy           string             `json:"leak_policy"`
	LeakMaxConcurrentIps pgtype.Int4        `json:"leak_max_concurrent_ips"`
	LeakMaxUniqueIps24h  pgtype.Int4        `json:"leak_max_unique_ips_24h"`
	Kind                 string             `json:"kind"`
	SocksUsername        pgtype.Text        `json:"socks_username"`
	SocksPassword        pgtype.Text        `json:"socks_password"`
	SocksPort            pgtype.Int4        `json:"socks_port"`
	PreferredExitID      pgtype.UUID        `json:"preferred_exit_id"`
}

type UserIpObservation struct {
	UserUuid     pgtype.UUID        `json:"user_uuid"`
	Ip           netip.Addr         `json:"ip"`
	FirstSeenAt  pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	SessionsSeen int64              `json:"sessions_seen"`
}

type UserLeakSignal struct {
	ID        int64              `json:"id"`
	UserUuid  pgtype.UUID        `json:"user_uuid"`
	Kind      string             `json:"kind"`
	Score     int32              `json:"score"`
	Detail    []byte             `json:"detail"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
