// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const enqueueNotification = `-- name: EnqueueNotification :exec
INSERT INTO notifications(user_uuid, telegram_id, type, payload, sent_at)
VALUES($1, $2, $3, $4, $5)
`

type EnqueueNotificationParams struct {
	UserUuid   pgtype.UUID        `json:"user_uuid"`
	TelegramID int64              `json:"telegram_id"`
	Type       string             `json:"type"`
	Payload    []byte             `json:"payload"`
	SentAt     pgtype.Timestamptz `json:"sent_at"`
}

func (q *Queries) EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) error {
	_, err := q.db.Exec(ctx, enqueueNotification,
		arg.UserUuid,
		arg.TelegramID,
		arg.Type,
		arg.Payload,
		arg.SentAt,
	)
	return err
}

const getAlertState = `-- name: GetAlertState :one
SELECT dedupe_key, type, severity, channel, status,
  consecutive_failures, consecutive_successes,
  last_seen_at, last_sent_at, last_payload, updated_at
FROM alert_state
WHERE dedupe_key=$1
`

func (q *Queries) GetAlertState(ctx context.Context, dedupeKey string) (AlertState, error) {
	row := q.db.QueryRow(ctx, getAlertState, dedupeKey)
	var i AlertState
	err := row.Scan(
		&i.DedupeKey,
		&i.Type,
		&i.Severity,
		&i.Channel,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.ConsecutiveSuccesses,
		&i.LastSeenAt,
		&i.LastSentAt,
		&i.LastPayload,
		&i.UpdatedAt,
	)
	return i, err
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notifications SET sent_at=NOW() WHERE id=$1
`

func (q *Queries) MarkNotificationSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markNotificationSent, id)
	return err
}

const pendingNotifications = `-- name: PendingNotifications :many
SELECT id, user_uuid, telegram_id, type, payload, sent_at, created_at
FROM notifications WHERE sent_at IS NULL ORDER BY created_at LIMIT $1
`

func (q *Queries) PendingNotifications(ctx context.Context, limit int32) ([]Notification, error) {
	rows, err := q.db.Query(ctx, pendingNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserUuid,
			&i.TelegramID,
			&i.Type,
			&i.Payload,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneOldIPObservations = `-- name: PruneOldIPObservations :execrows
DELETE FROM user_ip_observations
WHERE last_seen_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) PruneOldIPObservations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneOldIPObservations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneOldLeakSignals = `-- name: PruneOldLeakSignals :execrows
DELETE FROM user_leak_signals
WHERE created_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) PruneOldLeakSignals(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneOldLeakSignals)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneSentNotifications = `-- name: PruneSentNotifications :execrows
DELETE FROM notifications
WHERE sent_at IS NOT NULL AND sent_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) PruneSentNotifications(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneSentNotifications)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recentDistinctNotifications = `-- name: RecentDistinctNotifications :many
WITH ranked AS (
  SELECT id, user_uuid, telegram_id, type, payload, sent_at, created_at,
    ROW_NUMBER() OVER (
      PARTITION BY COALESCE(payload->>'dedupe_key', type || ':' || payload::text)
      ORDER BY created_at DESC, id DESC
    ) AS rn
  FROM notifications
)
SELECT id, user_uuid, telegram_id, type, payload, sent_at, created_at
FROM ranked
WHERE rn=1
ORDER BY created_at DESC, id DESC
LIMIT $1
`

type RecentDistinctNotificationsRow struct {
	ID         int64              `json:"id"`
	UserUuid   pgtype.UUID        `json:"user_uuid"`
	TelegramID int64              `json:"telegram_id"`
	Type       string             `json:"type"`
	Payload    []byte             `json:"payload"`
	SentAt     pgtype.Timestamptz `json:"sent_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) RecentDistinctNotifications(ctx context.Context, limit int32) ([]RecentDistinctNotificationsRow, error) {
	rows, err := q.db.Query(ctx, recentDistinctNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentDistinctNotificationsRow
	for rows.Next() {
		var i RecentDistinctNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserUuid,
			&i.TelegramID,
			&i.Type,
			&i.Payload,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentNotifications = `-- name: RecentNotifications :many
SELECT id, user_uuid, telegram_id, type, payload, sent_at, created_at
FROM notifications ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) RecentNotifications(ctx context.Context, limit int32) ([]Notification, error) {
	rows, err := q.db.Query(ctx, recentNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserUuid,
			&i.TelegramID,
			&i.Type,
			&i.Payload,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAlertState = `-- name: UpsertAlertState :exec
INSERT INTO alert_state(
  dedupe_key, type, severity, channel, status,
  consecutive_failures, consecutive_successes,
  last_seen_at, last_sent_at, last_payload, updated_at
)
VALUES($1,$2,$3,$4,$5,$6,$7,NOW(),$8,$9,NOW())
ON CONFLICT (dedupe_key) DO UPDATE SET
  type=EXCLUDED.type,
  severity=EXCLUDED.severity,
  channel=EXCLUDED.channel,
  status=EXCLUDED.status,
  consecutive_failures=EXCLUDED.consecutive_failures,
  consecutive_successes=EXCLUDED.consecutive_successes,
  last_seen_at=NOW(),
  last_sent_at=EXCLUDED.last_sent_at,
  last_payload=EXCLUDED.last_payload,
  updated_at=NOW()
`

type UpsertAlertStateParams struct {
	DedupeKey            string             `json:"dedupe_key"`
	Type                 string             `json:"type"`
	Severity             string             `json:"severity"`
	Channel              string             `json:"channel"`
	Status               string             `json:"status"`
	ConsecutiveFailures  int32              `json:"consecutive_failures"`
	ConsecutiveSuccesses int32              `json:"consecutive_successes"`
	LastSentAt           pgtype.Timestamptz `json:"last_sent_at"`
	LastPayload          []byte             `json:"last_payload"`
}

func (q *Queries) UpsertAlertState(ctx context.Context, arg UpsertAlertStateParams) error {
	_, err := q.db.Exec(ctx, upsertAlertState,
		arg.DedupeKey,
		arg.Type,
		arg.Severity,
		arg.Channel,
		arg.Status,
		arg.ConsecutiveFailures,
		arg.ConsecutiveSuccesses,
		arg.LastSentAt,
		arg.LastPayload,
	)
	return err
}
