// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: traffic.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLastSeenAll = `-- name: GetLastSeenAll :many
SELECT user_uuid, MAX(collected_at)::timestamptz AS last_seen
FROM traffic_stats
WHERE uplink_bytes + downlink_bytes > 0
GROUP BY user_uuid
`

type GetLastSeenAllRow struct {
	UserUuid pgtype.UUID        `json:"user_uuid"`
	LastSeen pgtype.Timestamptz `json:"last_seen"`
}

func (q *Queries) GetLastSeenAll(ctx context.Context) ([]GetLastSeenAllRow, error) {
	rows, err := q.db.Query(ctx, getLastSeenAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLastSeenAllRow
	for rows.Next() {
		var i GetLastSeenAllRow
		if err := rows.Scan(&i.UserUuid, &i.LastSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyAll = `-- name: GetMonthlyAll :many
SELECT user_uuid, year, month, uplink_bytes, downlink_bytes
FROM monthly_traffic WHERE year=$1 AND month=$2 ORDER BY user_uuid
`

type GetMonthlyAllParams struct {
	Year  int32 `json:"year"`
	Month int32 `json:"month"`
}

type GetMonthlyAllRow struct {
	UserUuid      pgtype.UUID `json:"user_uuid"`
	Year          int32       `json:"year"`
	Month         int32       `json:"month"`
	UplinkBytes   int64       `json:"uplink_bytes"`
	DownlinkBytes int64       `json:"downlink_bytes"`
}

func (q *Queries) GetMonthlyAll(ctx context.Context, arg GetMonthlyAllParams) ([]GetMonthlyAllRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyAll, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyAllRow
	for rows.Next() {
		var i GetMonthlyAllRow
		if err := rows.Scan(
			&i.UserUuid,
			&i.Year,
			&i.Month,
			&i.UplinkBytes,
			&i.DownlinkBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyHistory = `-- name: GetMonthlyHistory :many
SELECT year, month,
  SUM(uplink_bytes)::bigint AS uplink_bytes,
  SUM(downlink_bytes)::bigint AS downlink_bytes
FROM monthly_traffic
GROUP BY year, month
ORDER BY year DESC, month DESC
LIMIT $1
`

type GetMonthlyHistoryRow struct {
	Year          int32 `json:"year"`
	Month         int32 `json:"month"`
	UplinkBytes   int64 `json:"uplink_bytes"`
	DownlinkBytes int64 `json:"downlink_bytes"`
}

func (q *Queries) GetMonthlyHistory(ctx context.Context, limit int32) ([]GetMonthlyHistoryRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyHistoryRow
	for rows.Next() {
		var i GetMonthlyHistoryRow
		if err := rows.Scan(
			&i.Year,
			&i.Month,
			&i.UplinkBytes,
			&i.DownlinkBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyUser = `-- name: GetMonthlyUser :one
SELECT user_uuid, year, month, uplink_bytes, downlink_bytes
FROM monthly_traffic WHERE user_uuid=$1 AND year=$2 AND month=$3
`

type GetMonthlyUserParams struct {
	UserUuid pgtype.UUID `json:"user_uuid"`
	Year     int32       `json:"year"`
	Month    int32       `json:"month"`
}

type GetMonthlyUserRow struct {
	UserUuid      pgtype.UUID `json:"user_uuid"`
	Year          int32       `json:"year"`
	Month         int32       `json:"month"`
	UplinkBytes   int64       `json:"uplink_bytes"`
	DownlinkBytes int64       `json:"downlink_bytes"`
}

func (q *Queries) GetMonthlyUser(ctx context.Context, arg GetMonthlyUserParams) (GetMonthlyUserRow, error) {
	row := q.db.QueryRow(ctx, getMonthlyUser, arg.UserUuid, arg.Year, arg.Month)
	var i GetMonthlyUserRow
	err := row.Scan(
		&i.UserUuid,
		&i.Year,
		&i.Month,
		&i.UplinkBytes,
		&i.DownlinkBytes,
	)
	return i, err
}

const insertTrafficSample = `-- name: InsertTrafficSample :exec
INSERT INTO traffic_stats(user_uuid, collected_at, uplink_bytes, downlink_bytes)
VALUES($1, $2, $3, $4)
`

type InsertTrafficSampleParams struct {
	UserUuid      pgtype.UUID        `json:"user_uuid"`
	CollectedAt   pgtype.Timestamptz `json:"collected_at"`
	UplinkBytes   int64              `json:"uplink_bytes"`
	DownlinkBytes int64              `json:"downlink_bytes"`
}

func (q *Queries) InsertTrafficSample(ctx context.Context, arg InsertTrafficSampleParams) error {
	_, err := q.db.Exec(ctx, insertTrafficSample,
		arg.UserUuid,
		arg.CollectedAt,
		arg.UplinkBytes,
		arg.DownlinkBytes,
	)
	return err
}

const pruneOldTrafficSamples = `-- name: PruneOldTrafficSamples :execrows
DELETE FROM traffic_stats WHERE collected_at < $1
`

func (q *Queries) PruneOldTrafficSamples(ctx context.Context, collectedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, pruneOldTrafficSamples, collectedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const trafficTimeline1d = `-- name: TrafficTimeline1d :many
SELECT date_trunc('day', collected_at)::timestamptz AS bucket_start,
  COALESCE(SUM(uplink_bytes), 0)::bigint AS uplink_bytes,
  COALESCE(SUM(downlink_bytes), 0)::bigint AS downlink_bytes
FROM traffic_stats
WHERE user_uuid=$1 AND collected_at >= NOW() - $2::interval
GROUP BY bucket_start
ORDER BY bucket_start
`

type TrafficTimeline1dParams struct {
	UserUuid pgtype.UUID     `json:"user_uuid"`
	Column2  pgtype.Interval `json:"column_2"`
}

type TrafficTimeline1dRow struct {
	BucketStart   pgtype.Timestamptz `json:"bucket_start"`
	UplinkBytes   int64              `json:"uplink_bytes"`
	DownlinkBytes int64              `json:"downlink_bytes"`
}

func (q *Queries) TrafficTimeline1d(ctx context.Context, arg TrafficTimeline1dParams) ([]TrafficTimeline1dRow, error) {
	rows, err := q.db.Query(ctx, trafficTimeline1d, arg.UserUuid, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrafficTimeline1dRow
	for rows.Next() {
		var i TrafficTimeline1dRow
		if err := rows.Scan(&i.BucketStart, &i.UplinkBytes, &i.DownlinkBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trafficTimeline1h = `-- name: TrafficTimeline1h :many
SELECT date_trunc('hour', collected_at)::timestamptz AS bucket_start,
  COALESCE(SUM(uplink_bytes), 0)::bigint AS uplink_bytes,
  COALESCE(SUM(downlink_bytes), 0)::bigint AS downlink_bytes
FROM traffic_stats
WHERE user_uuid=$1 AND collected_at >= NOW() - $2::interval
GROUP BY bucket_start
ORDER BY bucket_start
`

type TrafficTimeline1hParams struct {
	UserUuid pgtype.UUID     `json:"user_uuid"`
	Column2  pgtype.Interval `json:"column_2"`
}

type TrafficTimeline1hRow struct {
	BucketStart   pgtype.Timestamptz `json:"bucket_start"`
	UplinkBytes   int64              `json:"uplink_bytes"`
	DownlinkBytes int64              `json:"downlink_bytes"`
}

func (q *Queries) TrafficTimeline1h(ctx context.Context, arg TrafficTimeline1hParams) ([]TrafficTimeline1hRow, error) {
	rows, err := q.db.Query(ctx, trafficTimeline1h, arg.UserUuid, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrafficTimeline1hRow
	for rows.Next() {
		var i TrafficTimeline1hRow
		if err := rows.Scan(&i.BucketStart, &i.UplinkBytes, &i.DownlinkBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trafficTimeline5m = `-- name: TrafficTimeline5m :many
SELECT (date_trunc('hour', collected_at) + ((extract(minute from collected_at)::int / 5) * interval '5 minutes'))::timestamptz AS bucket_start,
  COALESCE(SUM(uplink_bytes), 0)::bigint AS uplink_bytes,
  COALESCE(SUM(downlink_bytes), 0)::bigint AS downlink_bytes
FROM traffic_stats
WHERE user_uuid=$1 AND collected_at >= NOW() - $2::interval
GROUP BY bucket_start
ORDER BY bucket_start
`

type TrafficTimeline5mParams struct {
	UserUuid pgtype.UUID     `json:"user_uuid"`
	Column2  pgtype.Interval `json:"column_2"`
}

type TrafficTimeline5mRow struct {
	BucketStart   pgtype.Timestamptz `json:"bucket_start"`
	UplinkBytes   int64              `json:"uplink_bytes"`
	DownlinkBytes int64              `json:"downlink_bytes"`
}

func (q *Queries) TrafficTimeline5m(ctx context.Context, arg TrafficTimeline5mParams) ([]TrafficTimeline5mRow, error) {
	rows, err := q.db.Query(ctx, trafficTimeline5m, arg.UserUuid, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrafficTimeline5mRow
	for rows.Next() {
		var i TrafficTimeline5mRow
		if err := rows.Scan(&i.BucketStart, &i.UplinkBytes, &i.DownlinkBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trafficTimeline6h = `-- name: TrafficTimeline6h :many
SELECT (date_trunc('day', collected_at) + ((extract(hour from collected_at)::int / 6) * interval '6 hours'))::timestamptz AS bucket_start,
  COALESCE(SUM(uplink_bytes), 0)::bigint AS uplink_bytes,
  COALESCE(SUM(downlink_bytes), 0)::bigint AS downlink_bytes
FROM traffic_stats
WHERE user_uuid=$1 AND collected_at >= NOW() - $2::interval
GROUP BY bucket_start
ORDER BY bucket_start
`

type TrafficTimeline6hParams struct {
	UserUuid pgtype.UUID     `json:"user_uuid"`
	Column2  pgtype.Interval `json:"column_2"`
}

type TrafficTimeline6hRow struct {
	BucketStart   pgtype.Timestamptz `json:"bucket_start"`
	UplinkBytes   int64              `json:"uplink_bytes"`
	DownlinkBytes int64              `json:"downlink_bytes"`
}

func (q *Queries) TrafficTimeline6h(ctx context.Context, arg TrafficTimeline6hParams) ([]TrafficTimeline6hRow, error) {
	rows, err := q.db.Query(ctx, trafficTimeline6h, arg.UserUuid, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrafficTimeline6hRow
	for rows.Next() {
		var i TrafficTimeline6hRow
		if err := rows.Scan(&i.BucketStart, &i.UplinkBytes, &i.DownlinkBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMonthlyTraffic = `-- name: UpsertMonthlyTraffic :exec
INSERT INTO monthly_traffic(user_uuid, year, month, uplink_bytes, downlink_bytes, updated_at)
VALUES($1, $2, $3, $4, $5, NOW())
ON CONFLICT(user_uuid, year, month) DO UPDATE SET
  uplink_bytes = monthly_traffic.uplink_bytes + EXCLUDED.uplink_bytes,
  downlink_bytes = monthly_traffic.downlink_bytes + EXCLUDED.downlink_bytes,
  updated_at = NOW()
`

type UpsertMonthlyTrafficParams struct {
	UserUuid      pgtype.UUID `json:"user_uuid"`
	Year          int32       `json:"year"`
	Month         int32       `json:"month"`
	UplinkBytes   int64       `json:"uplink_bytes"`
	DownlinkBytes int64       `json:"downlink_bytes"`
}

func (q *Queries) UpsertMonthlyTraffic(ctx context.Context, arg UpsertMonthlyTrafficParams) error {
	_, err := q.db.Exec(ctx, upsertMonthlyTraffic,
		arg.UserUuid,
		arg.Year,
		arg.Month,
		arg.UplinkBytes,
		arg.DownlinkBytes,
	)
	return err
}
