// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cloneUserForUUIDRotation = `-- name: CloneUserForUUIDRotation :exec
INSERT INTO users(
  uuid, name, telegram_id, telegram_username, created_at, is_active, disabled_at,
  leak_policy, leak_max_concurrent_ips, leak_max_unique_ips_24h,
  kind, socks_username, socks_password, socks_port
)
SELECT
  $2, u.name, u.telegram_id, u.telegram_username, u.created_at, u.is_active, u.disabled_at,
  u.leak_policy, u.leak_max_concurrent_ips, u.leak_max_unique_ips_24h,
  u.kind, u.socks_username, u.socks_password, u.socks_port
FROM users u WHERE u.uuid=$1
`

type CloneUserForUUIDRotationParams struct {
	Uuid   pgtype.UUID `json:"uuid"`
	Uuid_2 pgtype.UUID `json:"uuid_2"`
}

func (q *Queries) CloneUserForUUIDRotation(ctx context.Context, arg CloneUserForUUIDRotationParams) error {
	_, err := q.db.Exec(ctx, cloneUserForUUIDRotation, arg.Uuid, arg.Uuid_2)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE uuid=$1
`

func (q *Queries) DeleteUser(ctx context.Context, uuid pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, uuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableUser = `-- name: DisableUser :execrows
UPDATE users SET is_active=false, disabled_at=NOW() WHERE uuid=$1 AND is_active=true
`

func (q *Queries) DisableUser(ctx context.Context, uuid pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, disableUser, uuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enableUser = `-- name: EnableUser :execrows
UPDATE users SET is_active=true, disabled_at=NULL WHERE uuid=$1
`

func (q *Queries) EnableUser(ctx context.Context, uuid pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, enableUser, uuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUser = `-- name: GetUser :one
SELECT uuid, name, kind, is_active, disabled_at,
  socks_username, socks_password, socks_port,
  leak_policy, leak_max_concurrent_ips, leak_max_unique_ips_24h
FROM users WHERE uuid=$1
`

type GetUserRow struct {
	Uuid                 pgtype.UUID        `json:"uuid"`
	Name                 string             `json:"name"`
	Kind                 string             `json:"kind"`
	IsActive             bool               `json:"is_active"`
	DisabledAt           pgtype.Timestamptz `json:"disabled_at"`
	SocksUsername        pgtype.Text        `json:"socks_username"`
	SocksPassword        pgtype.Text        `json:"socks_password"`
	SocksPort            pgtype.Int4        `json:"socks_port"`
	LeakPolicy           string             `json:"leak_policy"`
	LeakMaxConcurrentIps pgtype.Int4        `json:"leak_max_concurrent_ips"`
	LeakMaxUniqueIps24h  pgtype.Int4        `json:"leak_max_unique_ips_24h"`
}

func (q *Queries) GetUser(ctx context.Context, uuid pgtype.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, uuid)
	var i GetUserRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Kind,
		&i.IsActive,
		&i.DisabledAt,
		&i.SocksUsername,
		&i.SocksPassword,
		&i.SocksPort,
		&i.LeakPolicy,
		&i.LeakMaxConcurrentIps,
		&i.LeakMaxUniqueIps24h,
	)
	return i, err
}

const insertSocksUser = `-- name: InsertSocksUser :exec
INSERT INTO users(uuid, name, kind, socks_username, socks_password, socks_port)
VALUES($1, $2, 'socks5', $3, $4, $5)
`

type InsertSocksUserParams struct {
	Uuid          pgtype.UUID `json:"uuid"`
	Name          string      `json:"name"`
	SocksUsername pgtype.Text `json:"socks_username"`
	SocksPassword pgtype.Text `json:"socks_password"`
	SocksPort     pgtype.Int4 `json:"socks_port"`
}

func (q *Queries) InsertSocksUser(ctx context.Context, arg InsertSocksUserParams) error {
	_, err := q.db.Exec(ctx, insertSocksUser,
		arg.Uuid,
		arg.Name,
		arg.SocksUsername,
		arg.SocksPassword,
		arg.SocksPort,
	)
	return err
}

const insertVlessUser = `-- name: InsertVlessUser :exec
INSERT INTO users(uuid, name, kind) VALUES($1, $2, 'vless')
`

type InsertVlessUserParams struct {
	Uuid pgtype.UUID `json:"uuid"`
	Name string      `json:"name"`
}

func (q *Queries) InsertVlessUser(ctx context.Context, arg InsertVlessUserParams) error {
	_, err := q.db.Exec(ctx, insertVlessUser, arg.Uuid, arg.Name)
	return err
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT uuid, name, kind, is_active, disabled_at,
  socks_username, socks_password, socks_port,
  leak_policy, leak_max_concurrent_ips, leak_max_unique_ips_24h
FROM users WHERE is_active=true ORDER BY created_at
`

type ListActiveUsersRow struct {
	Uuid                 pgtype.UUID        `json:"uuid"`
	Name                 string             `json:"name"`
	Kind                 string             `json:"kind"`
	IsActive             bool               `json:"is_active"`
	DisabledAt           pgtype.Timestamptz `json:"disabled_at"`
	SocksUsername        pgtype.Text        `json:"socks_username"`
	SocksPassword        pgtype.Text        `json:"socks_password"`
	SocksPort            pgtype.Int4        `json:"socks_port"`
	LeakPolicy           string             `json:"leak_policy"`
	LeakMaxConcurrentIps pgtype.Int4        `json:"leak_max_concurrent_ips"`
	LeakMaxUniqueIps24h  pgtype.Int4        `json:"leak_max_unique_ips_24h"`
}

func (q *Queries) ListActiveUsers(ctx context.Context) ([]ListActiveUsersRow, error) {
	rows, err := q.db.Query(ctx, listActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveUsersRow
	for rows.Next() {
		var i ListActiveUsersRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Kind,
			&i.IsActive,
			&i.DisabledAt,
			&i.SocksUsername,
			&i.SocksPassword,
			&i.SocksPort,
			&i.LeakPolicy,
			&i.LeakMaxConcurrentIps,
			&i.LeakMaxUniqueIps24h,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT uuid, name, kind, is_active, disabled_at,
  socks_username, socks_password, socks_port,
  leak_policy, leak_max_concurrent_ips, leak_max_unique_ips_24h
FROM users ORDER BY created_at
`

type ListAllUsersRow struct {
	Uuid                 pgtype.UUID        `json:"uuid"`
	Name                 string             `json:"name"`
	Kind                 string             `json:"kind"`
	IsActive             bool               `json:"is_active"`
	DisabledAt           pgtype.Timestamptz `json:"disabled_at"`
	SocksUsername        pgtype.Text        `json:"socks_username"`
	SocksPassword        pgtype.Text        `json:"socks_password"`
	SocksPort            pgtype.Int4        `json:"socks_port"`
	LeakPolicy           string             `json:"leak_policy"`
	LeakMaxConcurrentIps pgtype.Int4        `json:"leak_max_concurrent_ips"`
	LeakMaxUniqueIps24h  pgtype.Int4        `json:"leak_max_unique_ips_24h"`
}

func (q *Queries) ListAllUsers(ctx context.Context) ([]ListAllUsersRow, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUsersRow
	for rows.Next() {
		var i ListAllUsersRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Kind,
			&i.IsActive,
			&i.DisabledAt,
			&i.SocksUsername,
			&i.SocksPassword,
			&i.SocksPort,
			&i.LeakPolicy,
			&i.LeakMaxConcurrentIps,
			&i.LeakMaxUniqueIps24h,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveIPObservationsUserUUID = `-- name: MoveIPObservationsUserUUID :exec
UPDATE user_ip_observations SET user_uuid=$2 WHERE user_uuid=$1
`

type MoveIPObservationsUserUUIDParams struct {
	UserUuid   pgtype.UUID `json:"user_uuid"`
	UserUuid_2 pgtype.UUID `json:"user_uuid_2"`
}

func (q *Queries) MoveIPObservationsUserUUID(ctx context.Context, arg MoveIPObservationsUserUUIDParams) error {
	_, err := q.db.Exec(ctx, moveIPObservationsUserUUID, arg.UserUuid, arg.UserUuid_2)
	return err
}

const moveLeakSignalsUserUUID = `-- name: MoveLeakSignalsUserUUID :exec
UPDATE user_leak_signals SET user_uuid=$2 WHERE user_uuid=$1
`

type MoveLeakSignalsUserUUIDParams struct {
	UserUuid   pgtype.UUID `json:"user_uuid"`
	UserUuid_2 pgtype.UUID `json:"user_uuid_2"`
}

func (q *Queries) MoveLeakSignalsUserUUID(ctx context.Context, arg MoveLeakSignalsUserUUIDParams) error {
	_, err := q.db.Exec(ctx, moveLeakSignalsUserUUID, arg.UserUuid, arg.UserUuid_2)
	return err
}

const moveMonthlyTrafficUserUUID = `-- name: MoveMonthlyTrafficUserUUID :exec
UPDATE monthly_traffic SET user_uuid=$2 WHERE user_uuid=$1
`

type MoveMonthlyTrafficUserUUIDParams struct {
	UserUuid   pgtype.UUID `json:"user_uuid"`
	UserUuid_2 pgtype.UUID `json:"user_uuid_2"`
}

func (q *Queries) MoveMonthlyTrafficUserUUID(ctx context.Context, arg MoveMonthlyTrafficUserUUIDParams) error {
	_, err := q.db.Exec(ctx, moveMonthlyTrafficUserUUID, arg.UserUuid, arg.UserUuid_2)
	return err
}

const moveNotificationsUserUUID = `-- name: MoveNotificationsUserUUID :exec
UPDATE notifications SET user_uuid=$2 WHERE user_uuid=$1
`

type MoveNotificationsUserUUIDParams struct {
	UserUuid   pgtype.UUID `json:"user_uuid"`
	UserUuid_2 pgtype.UUID `json:"user_uuid_2"`
}

func (q *Queries) MoveNotificationsUserUUID(ctx context.Context, arg MoveNotificationsUserUUIDParams) error {
	_, err := q.db.Exec(ctx, moveNotificationsUserUUID, arg.UserUuid, arg.UserUuid_2)
	return err
}

const moveTrafficStatsUserUUID = `-- name: MoveTrafficStatsUserUUID :exec
UPDATE traffic_stats SET user_uuid=$2 WHERE user_uuid=$1
`

type MoveTrafficStatsUserUUIDParams struct {
	UserUuid   pgtype.UUID `json:"user_uuid"`
	UserUuid_2 pgtype.UUID `json:"user_uuid_2"`
}

func (q *Queries) MoveTrafficStatsUserUUID(ctx context.Context, arg MoveTrafficStatsUserUUIDParams) error {
	_, err := q.db.Exec(ctx, moveTrafficStatsUserUUID, arg.UserUuid, arg.UserUuid_2)
	return err
}

const renameUser = `-- name: RenameUser :one
UPDATE users SET name=$1 WHERE uuid=$2
RETURNING uuid, name, kind, is_active, disabled_at,
  socks_username, socks_password, socks_port,
  leak_policy, leak_max_concurrent_ips, leak_max_unique_ips_24h
`

type RenameUserParams struct {
	Name string      `json:"name"`
	Uuid pgtype.UUID `json:"uuid"`
}

type RenameUserRow struct {
	Uuid                 pgtype.UUID        `json:"uuid"`
	Name                 string             `json:"name"`
	Kind                 string             `json:"kind"`
	IsActive             bool               `json:"is_active"`
	DisabledAt           pgtype.Timestamptz `json:"disabled_at"`
	SocksUsername        pgtype.Text        `json:"socks_username"`
	SocksPassword        pgtype.Text        `json:"socks_password"`
	SocksPort            pgtype.Int4        `json:"socks_port"`
	LeakPolicy           string             `json:"leak_policy"`
	LeakMaxConcurrentIps pgtype.Int4        `json:"leak_max_concurrent_ips"`
	LeakMaxUniqueIps24h  pgtype.Int4        `json:"leak_max_unique_ips_24h"`
}

func (q *Queries) RenameUser(ctx context.Context, arg RenameUserParams) (RenameUserRow, error) {
	row := q.db.QueryRow(ctx, renameUser, arg.Name, arg.Uuid)
	var i RenameUserRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Kind,
		&i.IsActive,
		&i.DisabledAt,
		&i.SocksUsername,
		&i.SocksPassword,
		&i.SocksPort,
		&i.LeakPolicy,
		&i.LeakMaxConcurrentIps,
		&i.LeakMaxUniqueIps24h,
	)
	return i, err
}

const rotateSocksPassword = `-- name: RotateSocksPassword :one
UPDATE users SET socks_password=$1 WHERE uuid=$2 AND kind='socks5' AND is_active=true
RETURNING uuid, name, kind, is_active, disabled_at,
  socks_username, socks_password, socks_port,
  leak_policy, leak_max_concurrent_ips, leak_max_unique_ips_24h
`

type RotateSocksPasswordParams struct {
	SocksPassword pgtype.Text `json:"socks_password"`
	Uuid          pgtype.UUID `json:"uuid"`
}

type RotateSocksPasswordRow struct {
	Uuid                 pgtype.UUID        `json:"uuid"`
	Name                 string             `json:"name"`
	Kind                 string             `json:"kind"`
	IsActive             bool               `json:"is_active"`
	DisabledAt           pgtype.Timestamptz `json:"disabled_at"`
	SocksUsername        pgtype.Text        `json:"socks_username"`
	SocksPassword        pgtype.Text        `json:"socks_password"`
	SocksPort            pgtype.Int4        `json:"socks_port"`
	LeakPolicy           string             `json:"leak_policy"`
	LeakMaxConcurrentIps pgtype.Int4        `json:"leak_max_concurrent_ips"`
	LeakMaxUniqueIps24h  pgtype.Int4        `json:"leak_max_unique_ips_24h"`
}

func (q *Queries) RotateSocksPassword(ctx context.Context, arg RotateSocksPasswordParams) (RotateSocksPasswordRow, error) {
	row := q.db.QueryRow(ctx, rotateSocksPassword, arg.SocksPassword, arg.Uuid)
	var i RotateSocksPasswordRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Kind,
		&i.IsActive,
		&i.DisabledAt,
		&i.SocksUsername,
		&i.SocksPassword,
		&i.SocksPort,
		&i.LeakPolicy,
		&i.LeakMaxConcurrentIps,
		&i.LeakMaxUniqueIps24h,
	)
	return i, err
}

const userSocksPortExists = `-- name: UserSocksPortExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE socks_port=$1)
`

func (q *Queries) UserSocksPortExists(ctx context.Context, socksPort pgtype.Int4) (bool, error) {
	row := q.db.QueryRow(ctx, userSocksPortExists, socksPort)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
