'use strict';
const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();
const app=document.querySelector('#app'),dialog=document.querySelector('#dialog'),nav=document.querySelector('#nav');
const selfMode=location.pathname==='/member';let currentTab='people',memberCache=[],subscription=null,subscriptionOwner=null,noticeTimer,refreshTimer;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,method='GET',body){const r=await fetch(path,{method,headers:{'X-Telegram-Init-Data':tg?.initData||'','Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});if(!r.ok){const e=new Error(r.status===401?'Откройте кабинет заново из личного чата с ботом.':r.status===403?'Для этого действия нет доступа.':r.status===409?'Состояние изменилось. Обновите экран и повторите действие.':'Операция временно недоступна. Попробуйте ещё раз.');e.status=r.status;if(path.startsWith('/api/cloud/')){try{const detail=await r.json();if(typeof detail.message==='string'&&detail.message.length<700)e.message=detail.message}catch{}}throw e}return r.status===204?null:r.json()}
function notice(t){const n=document.querySelector('#notice');n.textContent=t;n.hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>n.hidden=true,5000)}
function button(id,fn){const el=document.getElementById(id);if(el)el.onclick=async()=>{el.disabled=true;try{await fn()}catch(e){notice(e.message)}finally{el.disabled=false}}}
function modal(html){dialog.innerHTML=html+'<button class="btn secondary" id="close-dialog">Закрыть</button>';document.querySelector('#close-dialog').onclick=()=>dialog.close();dialog.showModal()}
function confirm(title,text,label,action){modal(`<h2>${esc(title)}</h2><p>${esc(text)}</p><button id="confirm-action" class="btn danger">${esc(label)}</button>`);button('confirm-action',async()=>{dialog.close();await action()})}
async function copy(text){try{await navigator.clipboard.writeText(text);notice('Ссылка скопирована')}catch{modal(`<h2>Скопируйте ссылку</h2><p class="secret">${esc(text)}</p>`)} }
function openExternal(url){const u=new URL(url);if(u.protocol!=='https:')throw new Error('Некорректная ссылка');if(tg?.openLink)tg.openLink(u.href);else window.open(u.href,'_blank','noopener,noreferrer')}
function status(m){return m.pending?'<span class="badge wait">Применяем изменение</span>':m.active?'<span class="badge good">Доступ готов</span>':'<span class="badge bad">Доступ отключён</span>'}
async function self(){clearTimeout(refreshTimer);const data=await api('/api/self');document.querySelector('#switch').hidden=!data.is_admin;
 if(!data.registered){app.innerHTML='<h1>Мой VPN</h1><div class="card"><h2>Личного доступа пока нет</h2><p>Для регистрации нужна ссылка из разрешённой группы или именное приглашение.</p>'+(data.is_admin?'<a class="btn" href="/#invites">Выдать именное приглашение</a><p class="muted">Администратор может пригласить свой Telegram-аккаунт.</p>':'')+'</div>';return}
 const m=data.member;if(subscriptionOwner!==m.uuid){subscription=null;subscriptionOwner=m.uuid}const ready=m.active&&!m.pending;
 app.innerHTML=`<h1>Мой VPN</h1><p class="muted">Одна подписка для всех ваших устройств</p><div class="card">${status(m)}<h2 class="spaced">${ready?'Подключитесь через Happ':m.pending?'Подтверждаем изменение на сервере':'Доступ приостановлен'}</h2><p class="muted">${ready?'Добавьте подписку один раз. Затем включайте VPN в Happ.':m.pending?'Повторная регистрация не нужна. Дождитесь подтверждения применения.':'Обратитесь к администратору. Новое приглашение не восстановит доступ.'}</p>${ready?'<button class="btn" id="connect">Подключить Happ</button><button class="btn secondary" id="copy-sub">Скопировать подписку</button><small>Не передавайте ссылку другим: она открывает доступ к VPN.</small>':''}</div>${ready?'<div class="card" id="locations">Загружаем локации…</div>':''}<button class="btn secondary" id="instructions">Как подключить устройство</button><button class="btn secondary" id="help">Не получается подключиться</button>`;
 button('instructions',instructions);button('help',()=>modal('<h2>Проверка подключения</h2><p>Откройте Happ, обновите подписку и включите VPN. При необходимости выберите другой профиль.</p><p>Если ошибка осталась, сообщите администратору устройство, сеть и время ошибки. Не отправляйте подписку, QR-код или ключ.</p>'));
 async function getSubscription(){if(!subscription)subscription=await api('/api/self/subscription','POST',{});return subscription}
 button('connect',async()=>openExternal((await getSubscription()).import_url));button('copy-sub',async()=>copy((await getSubscription()).url));
 if(ready)await locations();if(m.pending)refreshTimer=setTimeout(()=>self().catch(e=>notice(e.message)),5000)
}
async function locations(){const data=await api('/api/self/exits');const selected=data.selected_exit_id||'';const effective=data.exits.find(e=>e.id===data.effective_exit_id);
 document.querySelector('#locations').innerHTML=`<h2>Локация по умолчанию</h2><label for="preferred">Для профиля «Автоматически» в Happ</label><select id="preferred"><option value="">Автоматически</option>${data.exits.map(e=>`<option value="${esc(e.id)}" ${selected===e.id?'selected':''}>${esc(e.display_name)}${e.reachable?'':' · недоступна'}</option>`).join('')}</select><button class="btn secondary" id="save-location">Сохранить</button><p>Текущий выход: <strong>${esc(effective?.display_name||'Нет подтверждённого маршрута')}</strong></p><small>Выбор отдельной локации в Happ действует на это устройство. При отказе возможен резерв в другой стране.</small>${(data.profiles||[]).length?'<h3>Маршруты профилей Happ</h3>':''}${(data.profiles||[]).map(p=>`<p>${esc(p.name)} → ${esc(data.exits.find(e=>e.id===p.effective_exit_id)?.display_name||'Маршрут недоступен')}</p>`).join('')}<small>Кабинет не видит, какой профиль включён на устройстве.</small>`;
 button('save-location',async()=>{await api('/api/self/exit-selection','PUT',{exit_id:document.querySelector('#preferred').value||null});notice('Предпочтение сохранено. Проверяем применение.');await self()})
}
function instructions(){modal('<h2>Подключить устройство</h2><label for="device">Ваша система</label><select id="device"><option>iPhone / iPad</option><option>Android</option><option>macOS</option><option>Windows</option><option>Linux</option></select><ol><li>Установите Happ из официального источника.</li><li>Нажмите «Подключить Happ» в личном кабинете.</li><li>Подтвердите импорт и включите VPN.</li></ol><p>Если импорт не открылся, скопируйте подписку и добавьте её в Happ вручную. На своих устройствах используйте одну подписку.</p><a href="https://www.happ.su/" target="_blank" rel="noopener noreferrer">Официальный сайт Happ</a>')}
async function people(){memberCache=await api('/api/members');app.innerHTML='<div class="row"><h1>Люди</h1><button class="btn secondary" style="width:auto" id="invite-shortcut">Пригласить</button></div><input id="search" aria-label="Поиск" placeholder="Имя или Telegram ID"><select id="filter" aria-label="Статус"><option value="all">Все</option><option value="active">Активные</option><option value="disabled">Отключённые</option><option value="pending">Применяются</option></select><div id="people-list"></div><a class="link" href="/legacy.html">Ранее выданные конфиги</a>';button('invite-shortcut',()=>tab('invites'));document.querySelector('#search').oninput=drawPeople;document.querySelector('#filter').onchange=drawPeople;drawPeople()}
function drawPeople(){const q=document.querySelector('#search').value.toLowerCase(),filter=document.querySelector('#filter').value;const list=memberCache.filter(m=>(m.name.toLowerCase().includes(q)||String(m.telegram_id).includes(q))&&(filter==='all'||filter==='pending'&&m.pending||filter==='active'&&m.active||filter==='disabled'&&!m.active));document.querySelector('#people-list').innerHTML=list.map(m=>`<button class="person" data-member="${m.telegram_id}"><strong>${esc(m.name)}</strong><div class="row"><small>${m.telegram_id} · ${m.source==='group'?'Из группы':'По приглашению'}</small>${status(m)}</div></button>`).join('')||'<p class="muted">Пользователи не найдены</p>';document.querySelectorAll('[data-member]').forEach(el=>el.onclick=()=>person(memberCache.find(m=>String(m.telegram_id)===el.dataset.member)))}
function person(m){app.innerHTML=`<button class="btn secondary" id="back-people">Назад к людям</button><h1>${esc(m.name)}</h1><p class="muted">Telegram ID ${m.telegram_id}</p>${status(m)}<div class="card"><p>Регистрация: ${m.source==='group'?'Из группы':'Именное приглашение'}</p><p>${esc(new Date(m.enrolled_at).toLocaleDateString('ru'))}</p></div><button class="btn ${m.active?'danger':''}" id="toggle-access">${m.active?'Отключить':'Включить'} доступ</button><button class="btn secondary" id="reset-access">Сбросить на всех устройствах</button><small>Старые вручную выданные конфиги независимы от этого кабинета.</small>`;button('back-people',people);
 async function act(action){const updated=await api(`/api/members/${m.telegram_id}/action`,'POST',{action,expected_uuid:m.uuid});subscription=null;person(updated)}
 button('toggle-access',()=>confirm(m.active?'Отключить доступ?':'Включить доступ?',m.active?'Подписка и скачанные через неё конфиги перестанут работать. Ручные конфиги не затрагиваются.':'Прежняя подписка и конфиги снова будут действовать.',m.active?'Отключить':'Включить',()=>act(m.active?'disable':'enable')));
 button('reset-access',()=>confirm('Сбросить доступ на всех устройствах?','Старые конфиги и подписка перестанут работать. Пользователю потребуется заново импортировать подписку.','Сбросить доступ',()=>act('reset')))
}
async function invites(){const [group,list]=await Promise.all([api('/api/enrollment/group'),api('/api/enrollment/invites')]);app.innerHTML=`<h1>Приглашения</h1><div class="card"><h2>Именное приглашение</h2><p class="muted">Только выбранному аккаунту. Одно использование, срок — 7 дней.</p><button class="btn" id="native-invite">Выбрать получателя в боте</button><label for="recipient">Или числовой Telegram ID</label><input id="recipient" inputmode="numeric" placeholder="Telegram ID"><button class="btn secondary" id="invite-id">Продолжить</button></div><div class="card"><h2>Закрытая группа</h2><p>${esc(group.title||'Не настроена')} · ${group.enabled?'Регистрация открыта':'Регистрация закрыта'}</p><small>Выход из группы после регистрации не отключает VPN.</small>${group.enabled?'<button class="btn secondary" id="copy-group">Скопировать общую ссылку</button>':''}<label for="group-id">Telegram ID закрытой группы</label><input id="group-id" value="${group.chat_id||''}" inputmode="numeric"><button class="btn secondary" id="save-group">Проверить и включить</button>${group.chat_id?'<button class="btn secondary" id="disable-group">Закрыть регистрацию</button>':''}</div><h2>Выданные приглашения</h2>${list.map(i=>`<div class="card"><strong>Telegram ID ${i.recipient}</strong><p class="muted">${i.used_at?'Активировано':i.cancelled_at?'Отменено':new Date(i.expires_at)<new Date()?'Истекло':'До '+new Date(i.expires_at).toLocaleDateString('ru')}</p>${!i.used_at&&!i.cancelled_at?`<button class="btn secondary" data-cancel="${i.id}">Отменить</button>`:''}</div>`).join('')||'<p class="muted">Приглашений пока нет</p>'}`;
 button('native-invite',async()=>{await api('/api/enrollment/picker','POST',{});notice('Откройте личный чат с ботом: там появился выбор получателя.');tg?.close()});
 button('invite-id',()=>{const value=document.querySelector('#recipient').value;if(!/^[1-9]\d{0,14}$/.test(value))throw new Error('Введите числовой Telegram ID');confirm('Подтвердите получателя',`Пригласить Telegram ID ${value}? Административных прав приглашение не даёт.`,'Выдать приглашение',async()=>{const r=await api('/api/enrollment/invites','POST',{recipient:Number(value)});await copy(r.url);notice('Приглашение выдано и скопировано');await invites()})});
 button('copy-group',()=>copy(group.url));button('save-group',async()=>{const id=Number(document.querySelector('#group-id').value);if(!Number.isSafeInteger(id)||id>=0)throw new Error('Введите отрицательный Telegram ID группы');await api('/api/enrollment/group','PUT',{chat_id:id,enabled:true});await invites()});button('disable-group',()=>confirm('Закрыть регистрацию?','Уже выданный доступ сохранится. Именные приглашения продолжат работать.','Закрыть регистрацию',async()=>{await api('/api/enrollment/group','PUT',{chat_id:group.chat_id,title:group.title,enabled:false});await invites()}));
 document.querySelectorAll('[data-cancel]').forEach(el=>el.onclick=()=>confirm('Отменить приглашение?','Эта ссылка больше не позволит зарегистрироваться.','Отменить',async()=>{await api(`/api/enrollment/invites/${el.dataset.cancel}/cancel`,'POST',{});await invites()}))
}
const phases={prepare:'Подготовка',creating:'Проверяем создание VPS',install:'Установка Ultra',verify:'Проверка туннеля',publish:'Применение маршрутов',replace_old:'Удаление прежнего VPS',ready:'Готов',unpublish:'Отключение маршрута',delete:'Удаление VPS',cleanup:'Очистка ресурсов'};
async function service(){clearTimeout(refreshTimer);let ops=[],unavailable=false;try{ops=await api('/api/cloud/operations')}catch(e){if(e.status===401||e.status===403)throw e;unavailable=true}
 let replicas=[];try{replicas=await api('/api/cloud/replicas')}catch{}
 app.innerHTML=`<h1>Серверы</h1><p class="muted">Управление через Vultr · не более 2 VPS</p>${unavailable?'<div class="card"><h2>Vultr пока не настроен</h2><p>Для автоматизации нужны серверный API-ключ, SSH-ключ и настройки исполнителя.</p></div>':'<button class="btn" id="create-server">Создать exit</button>'}${ops.filter(o=>o.state!=='deleted'&&o.state!=='cancelled').map(o=>`<div class="card"><div class="row"><h2>${esc(o.offer.region.city)}</h2><span class="badge ${o.state==='ready'?'good':o.state==='failed'||o.state==='unknown'?'bad':'wait'}">${esc(phases[o.phase]||o.state)}</span></div><p>${esc(o.offer.plan.id)} · $${o.offer.price.monthly_cost}/месяц</p><p class="muted">${o.charged?'VPS оплачивается или результат создания ещё проверяется.':'Слот зарезервирован; покупка ещё не выполнена.'}</p>${o.error?`<p class="bad">${esc(o.error_message||o.error)}</p>`:''}${o.state==='ready'?`<button class="btn secondary" data-replace="${esc(o.id)}">Сменить регион</button>`:''}${o.state==='failed'||o.state==='unknown'?`<button class="btn secondary" data-action="retry" data-op="${esc(o.id)}">Повторить проверку / продолжить</button>`:''}<button class="btn secondary" data-events="${esc(o.id)}">Журнал операции</button>${o.instance_id?`<button class="btn danger" data-action="delete" data-op="${esc(o.id)}">Удалить сервер</button>`:o.phase==='prepare'?`<button class="btn secondary" data-action="cancel" data-op="${esc(o.id)}">Отменить создание</button>`:''}</div>`).join('')}<h2>Копии базы данных</h2><p class="muted">Основная БД на bridge. Восстановление — вручную.</p>${replicas.map(r=>`<div class="card"><strong>${esc(r.name)}</strong><p>${esc(({streaming:'Копия обновляется',syncing:'Первичная синхронизация',insufficient_space:'Недостаточно места',lagging:'Копия отстаёт',disconnected:'Нет потока репликации',unexpected_primary:'БД переведена в основную — требуется ручная проверка',error:'Требуется проверка',not_configured:'Ещё не настроена'})[r.state]||r.state)}</p><small>Свободно: ${(r.free_bytes/1073741824).toFixed(1)} ГБ · нужно для создания: ${(r.required_bytes/1073741824).toFixed(1)} ГБ</small></div>`).join('')||'<p class="muted">Состояние копий пока недоступно</p>'}<a class="link" href="/legacy.html#diag">Диагностика и статистика</a><a class="link" href="/legacy.html#settings">Настройки сервиса и администраторы</a><p class="muted">Узлы, настроенные вручную, обслуживаются через локальный установщик. Они продолжают участвовать в маршрутах.</p><button class="btn secondary" id="refresh-service">Обновить</button>`;
 document.querySelectorAll('[data-events]').forEach(el=>el.onclick=()=>operationEvents(el.dataset.events).catch(e=>notice(e.message)));
 button('create-server',()=>serverOffer(''));button('refresh-service',service);document.querySelectorAll('[data-replace]').forEach(el=>el.onclick=()=>serverOffer(el.dataset.replace).catch(e=>notice(e.message)));document.querySelectorAll('[data-op]').forEach(el=>el.onclick=()=>{const action=el.dataset.action;confirm(action==='delete'?'Удалить платный сервер?':'Продолжить операцию?',action==='delete'?'Сначала отключим маршрут. Удаление VPS необратимо; настройки локации сохранятся для резервного маршрута.':'Повтор продолжит сохранённую операцию. При неизвестном результате покупка не повторяется.',action==='delete'?'Удалить':'Продолжить',async()=>{await api(`/api/cloud/operations/${el.dataset.op}/action`,'POST',{action});await service()})});
 if(ops.some(o=>o.state==='pending'||o.state==='unknown'))refreshTimer=setTimeout(()=>{if(currentTab==='service')service().catch(e=>notice(e.message))},5000)
}
async function serverOffer(replace){const c=await api('/api/cloud/catalog');modal(`<h2>${replace?'Сменить регион':'Новый exit Vultr'}</h2><label for="region">Регион</label><select id="region">${c.regions.map(r=>`<option value="${esc(r.id)}" ${r.id==='fra'?'selected':''}>${esc(r.city)} · ${esc(r.country)}</option>`).join('')}</select><p>Тариф: 1 vCPU, 1 ГБ RAM, 25 ГБ SSD. Наличие и региональную цену проверим перед подтверждением.</p><button class="btn" id="quote">Проверить цену</button>`);button('quote',async()=>{const offer=await api('/api/cloud/offers','POST',{region:document.querySelector('#region').value,plan:'vc2-1c-1gb',replace_id:replace});dialog.close();modal(`<h2>Подтвердите покупку</h2><p>${esc(offer.region.city)} · ${esc(offer.plan.id)}</p><p><strong>$${offer.price.monthly_cost}/месяц · $${offer.price.hourly_cost}/час</strong></p><p>Трафик тарифа: ${offer.plan.bandwidth} ГБ. Квота начисляется по правилам Vultr; налоги и перерасход оплачиваются отдельно.</p><p class="muted">Предложение действует 5 минут. ${replace?'Новый сервер занимает дополнительный слот; старый удалим только после проверки и переключения.':''}</p><button class="btn" id="buy">Подтвердить создание платного VPS</button>`);button('buy',async()=>{await api(`/api/cloud/offers/${offer.id}/confirm`,'POST',{});dialog.close();await service()})})}
async function tab(name){clearTimeout(refreshTimer);currentTab=name;nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));app.textContent='Загрузка…';try{await({people,invites,service}[name]||people)()}catch(e){app.innerHTML=`<h1>Не удалось загрузить</h1><p>${esc(e.message)}</p><button class="btn secondary" id="retry-tab">Повторить</button>`;button('retry-tab',()=>tab(name))}}
(async()=>{try{if(selfMode){await self()}else{const me=await api('/api/me');if(!me.is_admin){location.replace('/member');return}nav.hidden=false;nav.querySelectorAll('button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));await tab(location.hash==='#invites'?'invites':'people')}}catch(e){app.innerHTML=`<h1>Кабинет недоступен</h1><p>${esc(e.message)}</p><p class="muted">Это не означает, что ранее выданный VPN отключён.</p><button class="btn secondary" id="retry-app">Повторить</button>`;button('retry-app',()=>location.reload())}})();
dialog.addEventListener('close',()=>{if(!dialog.open)dialog.innerHTML=''});
window.addEventListener('pagehide',()=>{subscription=null;dialog.innerHTML='';clearTimeout(refreshTimer)});

async function operationEvents(id){const events=await api(`/api/cloud/operations/${id}/events`);modal(`<h2>Журнал операции</h2><small>ID: ${esc(id)}</small>${events.map(e=>`<div class="card"><strong>${esc(phases[e.phase]||e.phase)}</strong><p>${esc(({started:'Начато',completed:'Завершено',waiting:'Ожидаем готовности VPS',failed:'Ошибка'})[e.outcome]||e.outcome)}</p><small>${esc(new Date(e.at).toLocaleString('ru'))} · ${(e.duration_ms/1000).toFixed(1)} с ${e.http_status?'· HTTP '+e.http_status:''}</small>${e.code?`<p>${esc(e.message||e.code)}</p>`:''}</div>`).join('')||'<p>Этапы ещё не запускались.</p>'}`)}
